# The URL the site will be built for
base_url = "https://mattbanister.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
# Put all your custom variables here

menu = [
    {url = "$BASE_URL", name = "home"},
    {url = "$BASE_URL/about", name = "about"},
]

linkedin_url = "https://www.linkedin.com/in/matthew-banister-15009921/"
github_url = "https://github.com/mattbanister"

